const mongoose = require('mongoose')

const screeningSchema = new mongoose.Schema({
    respondent_name: { type: String, required: true, trim: true },
    screening_date: { type: String, required: true, trim: true },
    type_of_respondent: { type: String, required: true, trim: true },
    support_person_type: { type: String, required: true, trim: true },
    support_person_name: { type: String, required: true, trim: true },
    age: { type: String, required: true, trim: true },
    caste: { type: String, required: true, trim: true },
    gest_age: { type: String, trim: true },
    education: { type: String, required: true, trim: true },
    school_status: { type: String, trim: true },
    type_of_school: { type: String, trim: true },
    school_name: { type: String, trim: true },
    block: { type: String, required: true, trim: true },
    village: { type: String, required: true, trim: true },
    anganwadi_center: { type: String, required: true, trim: true },
    sub_center: { type: String, required: true, trim: true },
    asha_name: { type: String, required: true, trim: true },
    anm_name: { type: String, required: true, trim: true },
    weight: { type: String, required: true, trim: true },
    height: { type: String, required: true, trim: true },
    bmi: { type: String, required: true, trim: true },
    service_question_one: { type: String, trim: true },
    service_question_two: { type: String, required: true, trim: true },
    service_question_three: { type: String, required: true, trim: true },
    service_question_four: { type: String, required: true, trim: true },
    status_question_one: { type: String, required: true, trim: true },
    status_hblevel: { type: String, required: true, trim: true },
    status_question_two: { type: String, required: true, trim: true },
    status_question_three: { type: String, required: true, trim: true },
    status_question_four: { type: String, required: true, trim: true },
    advices_description: { type: String, required: true, trim: true },
    blood_transfusion_center: { type: String, required: true, trim: true },
    blood_transfusion_date: { type: String, required: true, trim: true },
    screening_person_name: { type: String, required: true, trim: true },
    screening_person_desgination: { type: String, required: true, trim: true },
    screening_no: { type: String, required: true, trim: true },
    extra_note: { type: String, required: true, trim: true },
    isDeleted: { type: Boolean, default: false }
}, { timestamps: true })

module.exports = mongoose.model('Screening', screeningSchema)